name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 设置 Flutter 环境
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      # Step 3: 获取依赖
      - name: Install dependencies
        run: flutter pub get

      # Step 4: 静态代码检查
      - name: Run analyzer
        run: flutter analyze

      # Step 5: 运行测试
      - name: Run tests
        run: flutter test

      # Step 6: Run integration tests
      - name: Run integration tests
        run: flutter drive --target=test_driver/app.dart
      
      # Step 7: Upload coverage
      - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage/lcov.info

      # Step 8: Build APK
      #- name: Build APK
      #run: flutter build apk --release

      # Step 9: Build IPA
      #- name: Build IPA
      #run: flutter build ios --release

  deploy:
    runs-on: macos-latest
    needs: build-and-test
    steps:
      - name: Deployment step
        run: echo "This step can be configured to deploy your app to a store or server"
